allowing to serve as python backend

diff --git a/scripts/trtllm-serve b/scripts/trtllm-serve
--- a/scripts/trtllm-serve
+++ b/scripts/trtllm-serve
@@ -5,6 +5,34 @@ source "$SCRIPT_DIR/help/common.help"
 source "$SCRIPT_DIR/help/trtllm-serve.help"
 TAG=""
 
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[0;34m'
+NC='\033[0m' # No Color
+
+log() {
+    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"
+}
+
+success() {
+    echo -e "${GREEN}[SUCCESS]${NC} $1"
+}
+
+warning() {
+    echo -e "${YELLOW}[WARNING]${NC} $1"
+}
+
+error() {
+    echo -e "${RED}[ERROR]${NC} $1"
+    exit 1
+}
+
+soft_error() {
+    echo -e "${RED}[ERROR]${NC} $1"
+    exit 1
+}
+
 show_help() {
     show_trtllm_serve_help
 }
@@ -215,13 +243,9 @@ if [ -n "$SHOW_CONFIG_NAME" ]; then
 fi
 
 build_serve_command() {
-    local serve_cmd="trtllm-serve ${ENGINE_DIR} --tokenizer ${TOKENIZER_DIR}"
-
-    if [ "$BASIC_SERVE" = true ]; then
-        # Fallback to basic serve command
-        echo "$serve_cmd"
-        return
-    fi
+    local serve_args=""
+    local is_pytorch_backend=false
+    local extra_llm_api_options=""
 
     if [[ -n $SERVE_CONFIG ]]; then
       show_config "$SERVE_CONFIG" "\033[32m Using --serve-config $SERVE__CONFIG\033[0m"
@@ -232,11 +256,8 @@ build_serve_command() {
 
     # Check if the configuration exists
     if ! jq -e ".\"$SERVE_CONFIG\"" "$SERVE_ARGS_FILE" > /dev/null 2>&1; then
-        echo "Warning: Configuration '$SERVE_CONFIG' not found in serve-args.json"
-        echo "Available configurations:"
+        soft_error " Configuration '$SERVE_CONFIG' not found in serve-args.json\r\nAvailable configurations\r\n"
         jq -r 'keys[]' "$SERVE_ARGS_FILE" 2>/dev/null
-        echo "Using basic configuration..."
-        echo "$serve_cmd"
         exit 1
     fi
 
@@ -251,16 +272,28 @@ build_serve_command() {
                 continue
             fi
 
+            if [[ -n "$value" ]] && [[ "$key" == "--extra_llm_api_options" ]]; then
+              value="/extra_llm_api_options/$value"
+            fi
+
+            if [[ "$key" == "--backend" ]]; then
+              is_pytorch_backend=true
+            fi
+
             if [[ -n "$value" ]]; then
-                serve_cmd+=" $key $value"
+                serve_args+=" $key $value"
             else
-                serve_cmd+=" $key"
+                serve_args+=" $key"
             fi
             echo "Using serve config: $key $value"
         fi
     done < <(jq -r ".\"$SERVE_CONFIG\".args | to_entries[] | \"\(.key)=\(.value)\"" "$SERVE_ARGS_FILE" 2>/dev/null)
 
-    SERVE_COMMAND="$serve_cmd"
+    if [[ "$is_pytorch_backend" == true ]]; then
+      SERVE_COMMAND="trtllm-serve serve ${serve_args} ${TOKENIZER_DIR}"
+    else
+      SERVE_COMMAND="trtllm-serve ${ENGINE_DIR} --tokenizer ${TOKENIZER_DIR} ${serve_args}"
+    fi
 }
 
 echo "Starting TensorRT-LLM server for model '$MODEL', tag '$TAG', config '$SERVE_CONFIG'"
